server:
  port: 8081

spring:
  application:
    name: book-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  data:
    mongodb:
      uri: ${MONGODB_BARILIBRO_URI}

security:
  jwt:
    secret: ${JWT_SECRET_BARILIBRO}
    expiration: 86400000
