server:
  port: 8083

spring:
  application:
    name: purchase-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/bookstore
  kafka:
    bootstrap-servers: localhost:9092
    topic: purchases_topic
