server:
  port: 8082

spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/bookstore
  kafka:
    bootstrap-servers: localhost:9092
    topic: users_topic
security:
  jwt:
    secret: mySecretKey
    expiration: 86400000  # 1 día en milisegundos
