server:
  port: 8082

spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: ${MONGODB_BARILIBRO_URI}

security:
  jwt:
    secret: ${JWT_SECRET_BARILIBRO}
    expiration: 86400000
